x-logging: &default-logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"

services:
  db:
    <<: *default-logging
    image: postgres:15
    environment:
      POSTGRES_DB: translations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data 
      - ./app/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nt


  backend:
    <<: *default-logging
    build: ./backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/translations
    ports:
      - 3001:3001
    depends_on: 
      - transaltor

    networks:
      - nt

  frontend:
    <<: *default-logging
    build: ./frontend
    ports:
      - 8080:80

  transaltor:
    <<: *default-logging
    image: libretranslate/libretranslate
    ports:
      - 5000:5000
    networks:
      - nt
  # transaltor:
  #   image: libretranslate/libretranslate
  #   container_name: transaltor-1
  #   ports:
  #     - 5000:5000
  #   environment:
  #     - PYTHONHTTPSVERIFY=0
  #     - REQUESTS_CA_BUNDLE=""
  #     - CURL_CA_BUNDLE=""
  #     - NODE_TLS_REJECT_UNAUTHORIZED=0
  #     - PIP_TRUSTED_HOST=pypi.org pypi.python.org files.pythonhosted.org
    
 
volumes:
  postgres_data: {}

networks:
  nt:
    driver: bridge


