services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: translations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend_network

  backend:
    build: app/backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/translations
    networks:
      - backend_network
      - translator_network
    depends_on:
      - db
      - translator

  frontend:
    build: ./frontend
    ports:
      - 8080:80
    networks:
      - backend_network

  translator:
    image: libretranslate/libretranslate:latest
    container_name: app-translator-1
    ports:
      - 5000:5000
    networks:
      - backend_network
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs:ro  # זה "מזריק" את התעודות של המכונה לתוך הקונטיינר
    environment:
      - LT_LOAD_ONLY=en,he
      - LT_UPDATE_MODELS=false
      - SSL_CERT_DIR=/etc/ssl/certs      # אומר לפייתון איפה לחפש את התעודות
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    

volumes:
  db-data:

networks:
  backend_network:
    driver: bridge
  db_network:
    driver: bridge
  translator_network:
    driver: bridge