server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
    location /api/ {
        resolver kube-dns.kube-system.svc.cluster.local valid=10s ipv6=off;
        set $backend_upstream "http://backend-service.app-translator.svc.cluster.local:3001";
        proxy_pass $backend_upstream;
        proxy_connect_timeout 5s;
        proxy_read_timeout 180s;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
